export const create = async (req, res) => {
  try {
  } catch (error) {
    return res.status(500).json({
      message: error.message || "something went wrong",
    });
  }
};
export const getAll = async (req, res) => {
  try {
  } catch (error) {
    return res.status(500).json({
      message: error.message || "something went wrong",
    });
  }
};
export const getOne = async (req, res) => {
  try {
  } catch (error) {
    return res.status(500).json({
      message: error.message || "something went wrong",
    });
  }
};
export const update = async (req, res) => {
  try {
  } catch (error) {
    return res.status(500).json({
      message: error.message || "something went wrong",
    });
  }
};
export const remove = async (req, res) => {
  try {
  } catch (error) {
    return res.status(500).json({
      message: error.message || "something went wrong",
    });
  }
};
